[".config/tmux/plugins/tmux-sensible"]
# latest master as of 2026-08-03
url = "https://github.com/tmux-plugins/tmux-sensible/archive/5d089e418efb1a00f47654014ed085deb3d0c878.zip"
type = "archive"
extract = true
stripComponents = 1
refreshPeriod = "168h"  # 7 days
exact = true

[".config/tmux/plugins/vim-tmux-navigator"]
# latest master as of 2026-08-03
url = "https://github.com/christoomey/vim-tmux-navigator/archive/e41c431a0c7b7388ae7ba341f01a0d217eb3a432.zip"
type = "archive"
extract = true
stripComponents = 1
refreshPeriod = "168h"  # 7 days
exact = true

[".config/tmux/plugins/tmux-fzf"]
# latest master as of 2026-08-03
url = "https://github.com/sainnhe/tmux-fzf/archive/4cbbbbde54e1b63712d77483b83075fd712d3bb5.zip"
type = "archive"
extract = true
stripComponents = 1
refreshPeriod = "168h"  # 7 days
exact = true
