# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  #- id: trailing-whitespace
  #- id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: local
  hooks:
  - id: format-lua
    name: Format lua files
    language: system
    entry: mise run format-lua
    types: [lua]
  - id: nvim-lazy-lock-check
    name: Check neovim plugin lock file
    language: system
    entry: mise run nvim-lazy-lock-check
    pass_filenames: false
    always_run: true
  - id: nvim-spellfile-check
    name: Check neovim spellfile
    language: system
    entry: mise run nvim-spellfile-check
    pass_filenames: false
    always_run: true
