#!/bin/bash

# PROCEDURES IN THIS BOOTSTRAP SCRIPT SHOULD BE ABLE TO BE RERUN!


# Initialize stub kubeconfig to enable switching between contexts from configs
# in ~/.kube/config.d
init_kubeconfig() {
  if [ -f ~/.kube/config ]; then
    echo "Existing kubeconfig found. Current contents:"
    echo
    cat ~/.kube/config
    echo
    echo
    echo -n "Would you like to overwrite it with the skeleton kubeconfig? (Y/n) "
    read response
    case "$response" in
      n*|N*)
        echo "No changes made to kubeconfig"
        ;;
      y*|Y*|"")
        cp ~/.kube/config.skeleton ~/.kube/config
        ;;
      *)
        echo "Invalid response"
        init_kubeconfig
        ;;
    esac
  else
    cp ~/.kube/config.skeleton ~/.kube/config
  fi
}

add_tmux_plugin_manager() {
  if [ ! -d ~/.config/tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm.git ~/.config/tmux/plugins/tpm
  fi
}

init_kubeconfig
add_tmux_plugin_manager
yadm alt
