- name: Gather extra facts
  hosts: localhost
  tasks:
    - name: Check if yay is installed
      command: yay --version
      register: yay_version
      changed_when: false
      failed_when: false

- name: Pre-installation
  hosts: localhost
  roles:
    - role: jpedrodelacerda.yay
      when: ansible_os_family == 'Archlinux' and yay_version.rc != 0

- name: Install Archlinux packages
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Got yay?
      meta: end_play
      when: ansible_os_family != 'Archlinux'
      no_log: true

    - name: Update arch linux caches
      become: yes
      yay:
        update_cache: yes
      when: ansible_os_family == 'Archlinux'

    - name: Install arch linux packages
      yay:
        name: "{{ item.yay | default(item.name) }}"
        state: latest
      with_items: "{{ packages }}"
      when: >-
        ansible_os_family == 'Archlinux'
        and (
          item.tags is not defined
          or (item.tags | intersect(machine_tags[ansible_hostname]) | length) > 0
        )

- name: Install Apt packages
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Got apt?
      meta: end_play
      when: ansible_os_family != 'Debian'
      no_log: true

    - name: Update apt caches
      become: yes
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install apt packages
      become: yes
      apt:
        name: "{{ item.apt | default(item.name) }}"
        state: latest
      with_items: "{{ packages }}"
      when: >-
        ansible_os_family == 'Debian'
        and (
          item.tags is not defined
          or (item.tags | intersect(machine_tags[ansible_hostname]) | length) > 0
        )
