apiVersion: k3d.io/v1alpha5 
kind: Simple 
metadata:
  name: default
servers: 1
agents: 0
registries:
   create:
     name: docker-io # name of the registry container
     proxy:
       remoteURL: https://registry-1.docker.io # proxy DockerHub
       #username: <DOCKER_USERNAME>
       #password: <DOCKER_PASSWORD>
     volumes:
       - /tmp/reg:/var/lib/registry # persist data locally in /tmp/reg
   config: | # tell K3s to use this registry when pulling from DockerHub
     mirrors:
       "docker.io":
         endpoint:
           - http://docker-io:5000
  #config: | 
  #  mirrors:
  #    "docker.io":
  #      endpoint:
  #        - http://192.168.0.101:5000
  #    "quay.io":
  #      endpoint:
  #        - http://192.168.0.101:5001
  #    "ghcr.io":
  #      endpoint:
  #        - http://192.168.0.101:5002
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=cloud-controller
        nodeFilters:
          - server:*
      - arg: --disable=helm-controller
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
