set -u "_fisher_ilancosman_2F_tide_40_v5_files" "~/.config/fish/functions/_tide_1_line_prompt.fish" "~/.config/fish/functions/_tide_2_line_prompt.fish" "~/.config/fish/functions/_tide_cache_variables.fish" "~/.config/fish/functions/_tide_detect_os.fish" "~/.config/fish/functions/_tide_find_and_remove.fish" "~/.config/fish/functions/_tide_item_aws.fish" "~/.config/fish/functions/_tide_item_character.fish" "~/.config/fish/functions/_tide_item_chruby.fish" "~/.config/fish/functions/_tide_item_cmd_duration.fish" "~/.config/fish/functions/_tide_item_context.fish" "~/.config/fish/functions/_tide_item_crystal.fish" "~/.config/fish/functions/_tide_item_direnv.fish" "~/.config/fish/functions/_tide_item_distrobox.fish" "~/.config/fish/functions/_tide_item_docker.fish" "~/.config/fish/functions/_tide_item_elixir.fish" "~/.config/fish/functions/_tide_item_gcloud.fish" "~/.config/fish/functions/_tide_item_git.fish" "~/.config/fish/functions/_tide_item_go.fish" "~/.config/fish/functions/_tide_item_java.fish" "~/.config/fish/functions/_tide_item_jobs.fish" "~/.config/fish/functions/_tide_item_kubectl.fish" "~/.config/fish/functions/_tide_item_nix_shell.fish" "~/.config/fish/functions/_tide_item_node.fish" "~/.config/fish/functions/_tide_item_os.fish" "~/.config/fish/functions/_tide_item_php.fish" "~/.config/fish/functions/_tide_item_private_mode.fish" "~/.config/fish/functions/_tide_item_pulumi.fish" "~/.config/fish/functions/_tide_item_rustc.fish" "~/.config/fish/functions/_tide_item_shlvl.fish" "~/.config/fish/functions/_tide_item_status.fish" "~/.config/fish/functions/_tide_item_terraform.fish" "~/.config/fish/functions/_tide_item_time.fish" "~/.config/fish/functions/_tide_item_toolbox.fish" "~/.config/fish/functions/_tide_item_vi_mode.fish" "~/.config/fish/functions/_tide_item_virtual_env.fish" "~/.config/fish/functions/_tide_parent_dirs.fish" "~/.config/fish/functions/_tide_print_item.fish" "~/.config/fish/functions/_tide_pwd.fish" "~/.config/fish/functions/_tide_remove_unusable_items.fish" "~/.config/fish/functions/_tide_sub_bug-report.fish" "~/.config/fish/functions/_tide_sub_configure.fish" "~/.config/fish/functions/fish_mode_prompt.fish" "~/.config/fish/functions/fish_prompt.fish" "~/.config/fish/functions/tide" "~/.config/fish/functions/tide.fish" "~/.config/fish/conf.d/_tide_init.fish" "~/.config/fish/completions/tide.fish"
set -u "_fisher_jorgebucaran_2F_fisher_files" "~/.config/fish/functions/fisher.fish" "~/.config/fish/completions/fisher.fish"
set -u "_fisher_patrickf1_2F_fzf_2E_fish_files" "~/.config/fish/functions/_fzf_configure_bindings_help.fish" "~/.config/fish/functions/_fzf_extract_var_info.fish" "~/.config/fish/functions/_fzf_preview_changed_file.fish" "~/.config/fish/functions/_fzf_preview_file.fish" "~/.config/fish/functions/_fzf_report_diff_type.fish" "~/.config/fish/functions/_fzf_report_file_type.fish" "~/.config/fish/functions/_fzf_search_directory.fish" "~/.config/fish/functions/_fzf_search_git_log.fish" "~/.config/fish/functions/_fzf_search_git_status.fish" "~/.config/fish/functions/_fzf_search_history.fish" "~/.config/fish/functions/_fzf_search_processes.fish" "~/.config/fish/functions/_fzf_search_variables.fish" "~/.config/fish/functions/_fzf_wrapper.fish" "~/.config/fish/functions/fzf_configure_bindings.fish" "~/.config/fish/conf.d/fzf.fish" "~/.config/fish/completions/fzf_configure_bindings.fish"
set -u "_fisher_plugins" "jorgebucaran/fisher" "patrickf1/fzf.fish" "ilancosman/tide@v5"
set -u "_fisher_upgraded_to_4_4" 
set -u "tide_aws_bg_color" "normal"
set -u "tide_aws_color" "FF9900"
set -u "tide_aws_icon" ""
set -u "tide_character_color" "5FD700"
set -u "tide_character_color_failure" "FF0000"
set -u "tide_character_icon" "❯"
set -u "tide_character_vi_icon_default" "❮"
set -u "tide_character_vi_icon_replace" "▶"
set -u "tide_character_vi_icon_visual" "V"
set -u "tide_chruby_bg_color" "normal"
set -u "tide_chruby_color" "B31209"
set -u "tide_chruby_icon" ""
set -u "tide_cmd_duration_bg_color" "normal"
set -u "tide_cmd_duration_color" "87875F"
set -u "tide_cmd_duration_decimals" "0"
set -u "tide_cmd_duration_icon" 
set -u "tide_cmd_duration_threshold" "3000"
set -u "tide_context_always_display" "false"
set -u "tide_context_bg_color" "normal"
set -u "tide_context_color_default" "D7AF87"
set -u "tide_context_color_root" "D7AF00"
set -u "tide_context_color_ssh" "D7AF87"
set -u "tide_context_hostname_parts" "1"
set -u "tide_crystal_bg_color" "normal"
set -u "tide_crystal_color" "FFFFFF"
set -u "tide_crystal_icon" "⬢"
set -u "tide_direnv_bg_color" "normal"
set -u "tide_direnv_bg_color_denied" "normal"
set -u "tide_direnv_color" "D7AF00"
set -u "tide_direnv_color_denied" "FF0000"
set -u "tide_direnv_icon" "▼"
set -u "tide_distrobox_bg_color" "normal"
set -u "tide_distrobox_color" "FF00FF"
set -u "tide_distrobox_icon" "⬢"
set -u "tide_docker_bg_color" "normal"
set -u "tide_docker_color" "2496ED"
set -u "tide_docker_default_contexts" "default" "colima"
set -u "tide_docker_icon" ""
set -u "tide_elixir_bg_color" "normal"
set -u "tide_elixir_color" "4E2A8E"
set -u "tide_elixir_icon" ""
set -u "tide_gcloud_bg_color" "normal"
set -u "tide_gcloud_color" "4285F4"
set -u "tide_gcloud_icon" ""
set -u "tide_git_bg_color" "normal"
set -u "tide_git_bg_color_unstable" "normal"
set -u "tide_git_bg_color_urgent" "normal"
set -u "tide_git_color_branch" "5FD700"
set -u "tide_git_color_conflicted" "FF0000"
set -u "tide_git_color_dirty" "D7AF00"
set -u "tide_git_color_operation" "FF0000"
set -u "tide_git_color_staged" "D7AF00"
set -u "tide_git_color_stash" "5FD700"
set -u "tide_git_color_untracked" "00AFFF"
set -u "tide_git_color_upstream" "5FD700"
set -u "tide_git_icon" 
set -u "tide_git_truncation_length" "24"
set -u "tide_git_truncation_strategy" 
set -u "tide_go_bg_color" "normal"
set -u "tide_go_color" "00ACD7"
set -u "tide_go_icon" ""
set -u "tide_java_bg_color" "normal"
set -u "tide_java_color" "ED8B00"
set -u "tide_java_icon" ""
set -u "tide_jobs_bg_color" "normal"
set -u "tide_jobs_color" "5FAF00"
set -u "tide_jobs_icon" ""
set -u "tide_kubectl_bg_color" "normal"
set -u "tide_kubectl_color" "326CE5"
set -u "tide_kubectl_icon" "⎈"
set -u "tide_left_prompt_frame_enabled" "false"
set -u "tide_left_prompt_items" "pwd" "git" "newline" "character"
set -u "tide_left_prompt_prefix" ""
set -u "tide_left_prompt_separator_diff_color" " "
set -u "tide_left_prompt_separator_same_color" " "
set -u "tide_left_prompt_suffix" " "
set -u "tide_nix_shell_bg_color" "normal"
set -u "tide_nix_shell_color" "7EBAE4"
set -u "tide_nix_shell_icon" ""
set -u "tide_node_bg_color" "normal"
set -u "tide_node_color" "44883E"
set -u "tide_node_icon" "⬢"
set -u "tide_os_bg_color" "normal"
set -u "tide_os_color" "normal"
set -u "tide_os_icon" ""
set -u "tide_php_bg_color" "normal"
set -u "tide_php_color" "617CBE"
set -u "tide_php_icon" ""
set -u "tide_private_mode_bg_color" "normal"
set -u "tide_private_mode_color" "FFFFFF"
set -u "tide_private_mode_icon" "﫸"
set -u "tide_prompt_add_newline_before" "false"
set -u "tide_prompt_color_frame_and_connection" "6C6C6C"
set -u "tide_prompt_color_separator_same_color" "949494"
set -u "tide_prompt_icon_connection" " "
set -u "tide_prompt_min_cols" "34"
set -u "tide_prompt_pad_items" "false"
set -u "tide_pulumi_bg_color" "normal"
set -u "tide_pulumi_color" "F7BF2A"
set -u "tide_pulumi_icon" ""
set -u "tide_pwd_bg_color" "normal"
set -u "tide_pwd_color_anchors" "00AFFF"
set -u "tide_pwd_color_dirs" "0087AF"
set -u "tide_pwd_color_truncated_dirs" "8787AF"
set -u "tide_pwd_icon" 
set -u "tide_pwd_icon_home" 
set -u "tide_pwd_icon_unwritable" ""
set -u "tide_pwd_markers" ".bzr" ".citc" ".git" ".hg" ".node-version" ".python-version" ".ruby-version" ".shorten_folder_marker" ".svn" ".terraform" "Cargo.toml" "composer.json" "CVS" "go.mod" "package.json"
set -u "tide_right_prompt_frame_enabled" "false"
set -u "tide_right_prompt_items" "status" "cmd_duration" "context" "jobs" "direnv" "node" "virtual_env" "rustc" "java" "php" "pulumi" "chruby" "go" "gcloud" "kubectl" "distrobox" "toolbox" "terraform" "aws" "nix_shell" "crystal" "elixir" "time"
set -u "tide_right_prompt_prefix" " "
set -u "tide_right_prompt_separator_diff_color" " "
set -u "tide_right_prompt_separator_same_color" " "
set -u "tide_right_prompt_suffix" ""
set -u "tide_rustc_bg_color" "normal"
set -u "tide_rustc_color" "F74C00"
set -u "tide_rustc_icon" ""
set -u "tide_shlvl_bg_color" "normal"
set -u "tide_shlvl_color" "d78700"
set -u "tide_shlvl_icon" ""
set -u "tide_shlvl_threshold" "1"
set -u "tide_status_bg_color" "normal"
set -u "tide_status_bg_color_failure" "normal"
set -u "tide_status_color" "5FAF00"
set -u "tide_status_color_failure" "D70000"
set -u "tide_status_icon" "✔"
set -u "tide_status_icon_failure" "✘"
set -u "tide_terraform_bg_color" "normal"
set -u "tide_terraform_color" "844FBA"
set -u "tide_terraform_icon" 
set -u "tide_time_bg_color" "normal"
set -u "tide_time_color" "5F8787"
set -u "tide_time_format" "%T"
set -u "tide_toolbox_bg_color" "normal"
set -u "tide_toolbox_color" "613583"
set -u "tide_toolbox_icon" "⬢"
set -u "tide_vi_mode_bg_color_default" "normal"
set -u "tide_vi_mode_bg_color_insert" "normal"
set -u "tide_vi_mode_bg_color_replace" "normal"
set -u "tide_vi_mode_bg_color_visual" "normal"
set -u "tide_vi_mode_color_default" "949494"
set -u "tide_vi_mode_color_insert" "87AFAF"
set -u "tide_vi_mode_color_replace" "87AF87"
set -u "tide_vi_mode_color_visual" "FF8700"
set -u "tide_vi_mode_icon_default" "D"
set -u "tide_vi_mode_icon_insert" "I"
set -u "tide_vi_mode_icon_replace" "R"
set -u "tide_vi_mode_icon_visual" "V"
set -u "tide_virtual_env_bg_color" "normal"
set -u "tide_virtual_env_color" "00AFAF"
set -u "tide_virtual_env_icon" ""