# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
templates:
  params:
    author-email: "ryan@barth.tech"
    author-name: "Ryan Barth"
    copyright: "BSD"
    github-username: "r-bar"
